---
- name: Ensure app_path directory exists.
  file:
    path: "{{ app_path }}"
    state: directory
    mode: 0775
  sudo: no
  when: app.stat.exists == false

- name: Generate Openapphack app with Openapphack Generators.
  command: >
    chdir={{ app_path }}}
    {{ item }}
  with_items: generator_instructions | list
  when: app.stat.exists == false and generator_instructions | length
  sudo: no
